version: "3"

services:
  apisix:
    image: apache/apisix:3.10.0-debian
    restart: always
    deploy:
      resources:
        # limits:
        #   memory: "8000m"   # Limit memory usage to 512MB
        #   cpus: "8"      # Limit CPU usage to 1.5 CPUs
        reservations:
          memory: "4096m"   # Reserve 256MB memory (optional)
          cpus: "4"      # Reserve 0.5 CPUs (optional)
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./openapi.yaml:/usr/local/apisix/conf/openapi.yaml:ro
      - /tmp/runner.sock:/tmp/runner.sock
      - ./cache-encryption-key.key:/usr/local/apisix/conf/cache-encryption-key.key:ro

    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    image: apache/apisix-dashboard
    volumes:
      - ./dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    depends_on:
      - apisix
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:


networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
